### ISSUE TITLE
missing license text

### ISSUE THREAD

**Issue by mrsolo** [samuel/go-parser#1]
please supply the license information as i don't know which license is go-parser under

thanks

**Comment by harspras** [comment]
@samuel Any updates regarding the **license information** for **go-parser**?

**Comment by samuel** [comment]
Added a readme and license (3-clause BSD). TBH I would recommend https://github.com/PuerkitoBio/pigeon instead of this package

**Comment by harspras** [comment]
@samuel Thank you for your response. This package was being used in your go-thrift package in one of the earlier commits. In the most recent commit, this package is no longer being used I guess. Still thank you so much for your prompt response.
